
services:
  vue-app:
    build:
      dockerfile: Dockerfile
    container_name: vue-project
    working_dir: /app
    volumes:
      - .:/app
    # ホストの 5173 ポートをコンテナの 5173 ポートにマッピング。vite.configにも設定を追加
    ports:
      - "5173:5173"

  storybook:
    build:
      dockerfile: Dockerfile
    container_name: storybook-project
    working_dir: /app
    command: ["npm", "run", "storybook"]
    volumes:
      - .:/app
    ports:
      - "6006:6006"  # Storybookのポート
